### ISSUE TITLE
Construct a voting report

### ISSUE THREAD

**Issue by offbyone** [WorldconVotingSystems/nomnom#119]

**Comment by offbyone** [comment]
By the end of voting, probably, or at least I think we can.

**Comment by offbyone** [comment]
Looking more closely at that report, no, I will not be able to generate it, as NomNom does not have the canonicalized nomination data (and won't, at least til Seattle).

Honestly, NomNom shouldn't be doing the pretty-formatted stuff like that. It's not my forte. Those are clearly the result of a pile of Excel work, which is great, because what NomNom should give you is the input to those Excel sheets. What does that need to be?

**Comment by uwbookwyrm** [comment]
I think we have two report needs: 1) raw data that spits out for those who voted: how they ranked each finalist, and then the user info fields that are in the nominations report.

a second report is ideal that matches the yellow table on page six of the link provided - the voter runoff tables. On that link the green tables are the nominations data and the yellow are the voter runoff tables - with the tabulation occurring in NomNom, we’d prefer to be able to get a report with the calculations being run- does that make sense?

**Comment by offbyone** [comment]
So you want a live visualization of the current runoff data? Not a report, per se, but a way to see the current state of the category?

**Comment by uwbookwyrm** [comment]
I think we want the ability to download that visualization at the end of voting yes - and probably yes for seeing it currently?

**Comment by offbyone** [comment]
Okay. That'll make it necessary to have "No Award" be special in some way, which is not ideal but I can work with it.
