### ISSUE TITLE
Ensure that voting meets WSFS criteria for submission

### ISSUE THREAD

**Issue by offbyone** [WorldconVotingSystems/nomnom#120]
```[tasklist]
### Tasks
- [ ] Clean up the wording of the submission paragraph on the left
- [ ] Replace "WSFS mumbo jumbo here" in the footer with whatever WSFS actually wants.
```

**Comment by uwbookwyrm** [comment]
Attached is a copy of the text for this - we'd like it if it mirrored how nominations went with the instructions being on top followed by the ballot. Exception being the signature bit, if that could show as near to the "Submit" button as possible that would be great. 
[Online Text.docx](https://github.com/WorldconVotingSystems/nomnom/files/14858705/Online.Text.docx)
