### ISSUE TITLE
Vote Results Tabulation

### ISSUE THREAD

**Issue by uwbookwyrm** [WorldconVotingSystems/nomnom#122]
6.4 of the constitution for how to tabulate. Additional details from Nicholas: 

Votes shall first be tallied by the voter’s first choices.

If no majority is then obtained, the candidate who places last in the initial tallying shall be eliminated and the ballots listing it as first choice shall be redistributed to remaining candidates on the basis of those ballots’ second choices.

This process shall be repeated, using the next available preference from eliminated candidates’ ballots, until a majority-vote winner is obtained. If a preference below the first preference in the ballot has been left blank, no further preferences are counted for that ballot.

If two or more candidates are tied for elimination during this process, the candidate that received fewer first-place votes shall be eliminated.

If they are still tied, all the tied candidates shall be eliminated together

### Notes

```[tasklist]
- [x] Tabulate the first place votes
- [ ] https://github.com/WorldconVotingSystems/nomnom/issues/144
```

**Comment by offbyone** [comment]
The main job is done.
