### ISSUE TITLE
Voting Warnings

### ISSUE THREAD

**Issue by uwbookwyrm** [WorldconVotingSystems/nomnom#127]
When a user forgets a number in a sequence or selects a number twice in a sequence, can an error be generated that indicates this has occurred? Basically have an alert that the vote cannot be submitted if preferences are duplicated or skipped. 

For example, John Doe goes to vote for Best Novel and inputs a choice for 2,3,4,5 - the ballot should give an error indicating that numbers cannot be skipped.

**Comment by offbyone** [comment]
So, just to be clear, "unranked" is still a valid choice, but a sequence with missing numbers is not?

**Comment by uwbookwyrm** [comment]
Correct
