### ISSUE TITLE
Updating top of text

### ISSUE THREAD

**Issue by uwbookwyrm** [WorldconVotingSystems/nomnom#134]
Attached is text for the top of the ballot

We need the day/time it closes to match the style of DAY, DD Month YEAR, Time if possible for style purposes. There is also a link to the wsfs constitution that it'd be great to have as a link. 

[Top of the Text.docx](https://github.com/WorldconVotingSystems/nomnom/files/15017375/Top.of.the.Text.docx)

**Comment by offbyone** [comment]
I don't know how to interpret `DAY, DD Month YEAR`; can you give an example?

**Comment by offbyone** [comment]
I figured it out; this is done now.
