### ISSUE TITLE
Adding Manual votes

### ISSUE THREAD

**Issue by uwbookwyrm** [WorldconVotingSystems/nomnom#148]
Add the ability to add in manual votes mailed in. Would be great if it functioned like adding in the nominating mailed in ones where we could add via the "nominating" member profile and select the link "add votes".

**Comment by offbyone** [comment]
@uwbookwyrm can you confirm, I believe this works now.

**Comment by uwbookwyrm** [comment]
tested and appears to work :) thanks so much!
