### ISSUE TITLE
Advisory Vote: Preview Permission

### ISSUE THREAD

**Issue by NotthegoatRosemary** [WorldconVotingSystems/nomnom#160]
Please add preview permission to Nicholas, Rosemary, and Cassidy.

**Comment by offbyone** [comment]
Is this a general request for the ability to preview vote text, or a request for preview access for something else?

**Comment by NotthegoatRosemary** [comment]
Hi! Thanks for getting back to me.
This is a request to preview what the page will look like when the voters
go to it. I would like to preview any changes I make to the text with the
markdown formatting. Is that what you mean for the general request?
—Rosemary

**Comment by offbyone** [comment]
Yup, can do.

**Comment by NotthegoatRosemary** [comment]
Sweet! I appreciate you.

**Comment by NotthegoatRosemary** [comment]
Any idea when you’ll be able to do this for me? Do you mind sending me a
message when it’s done, or will GitHub tell me the ticket is closed? It
isn’t urgent, it just helps me to know. Thanks!

**Comment by NotthegoatRosemary** [comment]
Awesome! Thank you

**Comment by offbyone** [comment]
This should be in place after the latest update.

You can now reach a custom preview view from the admin page itself via the "View on Site" button at the top of the page near the totals:

![Image](https://github.com/user-attachments/assets/9b704f77-5244-4869-8dd3-a7bca4f23a3d)

That'll jump directly to the page with the text exactly as the members will see it when the vote is open.

**Comment by NotthegoatRosemary** [comment]
Beautiful, I’ll be able to see my own whole ass thing - this is really
helpful. Very appreciate.
