### ISSUE TITLE
Disqualify a Hugo Vote

### ISSUE THREAD

**Issue by uwbookwyrm** [WorldconVotingSystems/nomnom#163]
We'd like to have the ability if we determine a vote is not valid under the Constitution to disqualify the vote within the system and have it removed from the voting results. - specifically the Hugo Award Votes (and for the future the nominating stage as well).

**Comment by offbyone** [comment]
To most effectively do this, use two new features introduced in #164: 

1. Filtering ranks by member
2. Bulk invalidation

The filter can be found in the rank admin view at `/admin/nominate/rank`; simply identify the member whose ballot should be invalidated, select all of the ranks for it, and then choose "Mark invalid" from the dropdown:

![Image](https://github.com/user-attachments/assets/3fa7907f-074d-451a-9686-626e02e801ee)
