### ISSUE TITLE
Email receipt showing too many nomination lines

### ISSUE THREAD

**Issue by katjonzz** [WorldconVotingSystems/nomnom#63]
From Marguerite Smith:
I get six entries in the email record (specifically for Short Story & Semiprozine), not five.

**Comment by offbyone** [comment]
I would need to see that email in order to address this.

**Comment by katjonzz** [comment]
Emailed that email to you at your Glasgow account.

**Comment by offbyone** [comment]
I would appreciate it if someone can check if this is still occurring, after a ballot has been updated.
