### ISSUE TITLE
Search on 'Nominations' page

### ISSUE THREAD

**Issue by katjonzz** [WorldconVotingSystems/nomnom#66]
Am concerned about this page becoming unwieldy once we have thousands (or tens of thousands) of individual nominations showing:
https://nominations.glasgow2024.org/admin/nominate/nomination/

Can a search function be added?
At a minimum, ability to search by User ID so we can easily invalidate nominations for a particular user if we need to
'Nice to have' would also be ability to search content of nominations, but am not stressed if we don't have that. We can download the .csv file and accomplish what we would need there.

**Comment by offbyone** [comment]
I've added this -- and plan to ship it to production tonight -- but you should be aware that the component that implements it is very, very shaky, and sometimes loses the ability to find autocompleted values. I can't attest to what it's going to do to site performance either.

Anyway, it's there. Use it with care please, and expect it to be flaky sometimes.
