### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by tim-schilling** [WorldconVotingSystems/nomnom#9]
- Something looks weird here: https://github.com/WorldconVotingSystems/nomnom/blob/main/nominate/views.py#L122C1-L126C77
- You probably want to make `member_id` unique here to avoid duplicate records for a person https://github.com/WorldconVotingSystems/nomnom/blob/main/nominate/models.py#L30
- Should these be unique across the relationship pair? https://github.com/WorldconVotingSystems/nomnom/blob/main/nominate/models.py#L75-L76 and https://github.com/WorldconVotingSystems/nomnom/blob/main/nominate/models.py#L134-L135
- Should this be a OneToOneField rather than ForeignKey? https://github.com/WorldconVotingSystems/nomnom/blob/main/nominate/models.py#L18C1-L20C6
- This should be an environment variable https://github.com/WorldconVotingSystems/nomnom/blob/main/nomnom/settings.py#L48
- There tend to be non-field errors for forms (https://github.com/WorldconVotingSystems/nomnom/blob/main/nominate/templates/nominate/nominate.html#L18) https://docs.djangoproject.com/en/5.0/ref/forms/api/#django.forms.Form.non_field_errors

stylistic opinions
- I like to use related_name for all relationship fields (ManyToManyField, ForeignKey, OneToOneField) https://docs.djangoproject.com/en/4.2/ref/models/fields/#django.db.models.ForeignKey.related_name
- These are used more than once and will result in multiple db hits. It's probably better to store it on the view as a member variable or cache it some way https://github.com/WorldconVotingSystems/nomnom/blob/main/nominate/views.py#L57-L61
- Adding pre-commit with black or ruff is nice (here's an example repo https://github.com/adamchainz/django-mysql/blob/main/.pre-commit-config.yaml)
- It's not necessary to define view methods when the parent class defines it: https://github.com/WorldconVotingSystems/nomnom/blob/main/nominate/views.py#L89C1-L90C53
- Django projects tend to have URLs with trailing /'s: https://github.com/WorldconVotingSystems/nomnom/blob/main/nominate/urls.py#L8

**Comment by jefftriplett** [comment]
[model-bakery](https://model-bakery.readthedocs.io/en/latest/) might save you some time when you start testing. 

Bonus points for using a pytest fixture with it.

**Comment by offbyone** [comment]
Thanks! I think I hit all of the must-do and most of the stylistic ones.

**Comment by tim-schilling** [comment]
Glad I could help! Let me know if I need to explain any reasoning further.
