### ISSUE TITLE
iOS ballot weirdness

### ISSUE THREAD

**Issue by katjonzz** [WorldconVotingSystems/nomnom#93]
Carolyn is accessing the ballot using Safari on her iPhone, with 'large text' enabled. She can only view the ballot in landscape orientation and very little of the screen is visible. In portrait mode she can't scroll side-to-side to see the whole ballot. I'll attach her screenshots in a moment.

I have a feeling you're going to say this is what you need the CSS person for? Or do you have any ideas? I'm sure she won't be the only person using that particular accessibilty feature on a phone browser.

**Comment by katjonzz** [comment]
![IMG_3643](https://github.com/WorldconVotingSystems/nomnom/assets/96961811/8b40b747-96df-4229-a1e2-33bd19173cb0)
![IMG_3642](https://github.com/WorldconVotingSystems/nomnom/assets/96961811/a957f525-7b60-4b3e-a5e7-18379a67bb6a)
![IMG_3641](https://github.com/WorldconVotingSystems/nomnom/assets/96961811/c1c2488d-b04a-49f1-993b-ae8deff2d850)
![IMG_3640](https://github.com/WorldconVotingSystems/nomnom/assets/96961811/1aa19b82-6158-42b9-8303-301e50d83e15)
![IMG_3638](https://github.com/WorldconVotingSystems/nomnom/assets/96961811/c2718ed2-cedb-4c25-bd8e-8e2b9753f1f9)

Landscape mode samples

**Comment by katjonzz** [comment]
![IMG_3645](https://github.com/WorldconVotingSystems/nomnom/assets/96961811/680aa409-b4ab-433f-b0b1-c6b0cd540e3a)
![IMG_3646](https://github.com/WorldconVotingSystems/nomnom/assets/96961811/cffbc2c1-7223-41b3-8f2b-8bd0e41d6481)
![IMG_3647](https://github.com/WorldconVotingSystems/nomnom/assets/96961811/0fb1ebbf-9715-46c8-b7ef-3e73b76f57c6)

Portrait orientation samples

**Comment by offbyone** [comment]
Ooof. Those are really not good.

Yeah, this is the stuff I am _not_ good at. I can *try* but no promises. You're right that it needs to be addressed.

**Comment by katjonzz** [comment]
Cassidy says they can try to help you with this tomorrow

**Comment by katjonzz** [comment]
Given the tight timeline, I think I'm okay with this one being fixed after noms open if necessary. The number of people who can only access the ballot via an iPhone with Large Text turned on (and no other device) should be small, we just need to get it fixed with plenty of time for them to get their noms in before the deadline. And we really are trying to get you that CSS help we've been promising.

**Comment by offbyone** [comment]
I believe I have a fix for this in #507f181

**Comment by offbyone** [comment]
This is fixed and deployed now.
