### ISSUE TITLE
Clickable crosses on ballot pop-up messages

### ISSUE THREAD

**Issue by katjonzz** [WorldconVotingSystems/nomnom#95]
I've received a report from a mobile user that when they try to click the X to close a pop-up message (ballot saved, problem with ballot, email sent) it's difficult to successfully select the X and most of the time it thinks she's clicking what's in the background (which is the banner that takes her to the main page). 

I think that means the input field around the X needs to be a larger area, so it will know someone is clicking the X if they're clicking slightly off the mark? What do you think?

Thanks!

**Comment by offbyone** [comment]
I'm gonna call this fixed in #131 by virtue of the toasts fading out on their own.
